const characters=[
{id:"debora",name:"Débora",role:"Profetisa e juíza de Israel",ref:"Juízes 4–5",initial:"D",intro:"Débora foi uma profetisa e juíza de Israel. Ela aparece em um período de opressão e participa da liderança que conduz Israel à vitória sobre Sísera.",facts:[["Função","Profetisa e juíza"],["Esposo","Lapidote"],["Livro","Juízes"],["Capítulos","4 e 5"]],people:["Baraque","Sísera","Jabim","Jael"],themes:["Coragem","Liderança","Fé","Obediência"],sections:[["Quem foi","Juízes 4:4 apresenta Débora como profetisa e juíza. Ela julgava Israel debaixo da palmeira de Débora."],["O chamado para a batalha","Débora chamou Baraque e transmitiu a ordem para reunir dez mil homens de Naftali e Zebulom para enfrentar Sísera (Juízes 4:6–7)."],["A batalha","O relato mostra que Deus deu vitória a Israel. Sísera fugiu, e Jael teve papel decisivo no desfecho (Juízes 4:12–22)."],["O cântico","Juízes 5 registra o cântico de Débora e Baraque, celebrando a vitória e mencionando as tribos que participaram ou ficaram de fora."]],note:"A Bíblia não informa a idade de Débora. O app deve apresentar como fato somente aquilo que o texto bíblico registra."]},
{id:"baraque",name:"Baraque",role:"Líder chamado por Débora",ref:"Juízes 4–5",initial:"B",intro:"Baraque recebeu de Débora a orientação para reunir homens e enfrentar o exército de Sísera.",facts:[["Função","Comandante de Israel"],["Livro","Juízes"],["Capítulos","4 e 5"],["Ligação","Débora"]],people:["Débora","Sísera","Jabim","Jael"],themes:["Coragem","Obediência","Batalha"],sections:[["Chamado","Débora chamou Baraque e transmitiu a ordem recebida do Senhor (Juízes 4:6–7)."],["A condição de Baraque","Baraque disse que iria se Débora fosse com ele (Juízes 4:8)."],["Vitória","Baraque reuniu os homens e perseguiu o exército de Sísera (Juízes 4:10–16)."]],note:"A Bíblia não fornece todos os detalhes pessoais da vida de Baraque; o estudo deve permanecer nas informações registradas."]},
{id:"davi",name:"Davi",role:"Rei de Israel",ref:"1 Samuel 16 – 1 Reis 2",initial:"D",intro:"Davi é apresentado como pastor, guerreiro, salmista e rei de Israel.",facts:[["Função","Rei de Israel"],["Pai","Jessé"],["Tribo","Judá"],["Livros","1–2 Samuel"]],people:["Samuel","Saul","Jônatas","Bate-Seba"],themes:["Fé","Adoração","Liderança"],sections:[["Unção","Samuel ungiu Davi conforme a direção de Deus (1 Samuel 16)."],["Golias","Davi enfrentou Golias confiando no Senhor (1 Samuel 17)."],["Reinado","Davi tornou-se rei e marcou a história de Israel (2 Samuel)."]],note:"A vida de Davi possui muitos episódios e deve ser estudada em seu contexto bíblico."]}
];
const themes=[
["fé","Fé","Personagens, textos e acontecimentos relacionados à fé."],
["coragem","Coragem","Pessoas que enfrentaram desafios confiando em Deus."],
["liderança","Liderança","Princípios de liderança encontrados nas Escrituras."],
["oração","Oração","Textos e exemplos de oração na Bíblia."],
["obediência","Obediência","Chamados, decisões e respostas à vontade de Deus."],
["mulheres","Mulheres da Bíblia","Personagens femininas e suas histórias."]
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function go(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$(".bottom-nav button").forEach(x=>x.classList.toggle("nav-active",x.dataset.nav===id));window.scrollTo(0,0);if(id==="estudos")renderSaved()}
$$("[data-nav]").forEach(b=>b.addEventListener("click",()=>{let id=b.dataset.nav;if(id==="detail")return;go(id)}));
function card(c){return `<div class="character-card" data-person="${c.id}"><div class="person-avatar">${c.initial}</div><div><h3>${c.name}</h3><p>${c.role} · ${c.ref}</p></div></div>`}
function openPerson(id){let c=characters.find(x=>x.id===id);if(!c)return;$("#detailContent").innerHTML=`<div class="detail-card"><span class="tag">PERSONAGEM</span><h1>${c.name}</h1><p>${c.role}</p><div class="fact-grid">${c.facts.map(f=>`<div class="fact"><small>${f[0]}</small><b>${f[1]}</b></div>`).join("")}</div><p>${c.intro}</p>${c.sections.map(s=>`<div class="section"><h3>${s[0]}</h3><p>${s[1]}</p></div>`).join("")}<div class="section"><h3>Pessoas relacionadas</h3><div class="chips">${c.people.map(x=>`<span class="chip">${x}</span>`).join("")}</div></div><div class="section"><h3>Temas</h3><div class="chips">${c.themes.map(x=>`<span class="chip">${x}</span>`).join("")}</div></div><div class="section"><h3>⚠️ Informação importante</h3><p>${c.note}</p></div><button class="primary" style="margin-top:18px;width:100%" onclick="prefillOutline('${c.name}','${c.ref}')">📝 Criar esboço sobre ${c.name}</button></div>`;go("detail")}
function prefillOutline(name,ref){$("#outlineTopic").value=name;$("#outlineText").value=ref;go("esboco")}
function renderCharacters(){$("#characterGrid").innerHTML=characters.map(card).join("");$$("[data-person]").forEach(x=>x.onclick=()=>openPerson(x.dataset.person))}
function renderThemes(){$("#themeGrid").innerHTML=themes.map(t=>`<div class="theme-card"><h3>${t[1]}</h3><p>${t[2]}</p></div>`).join("")}
function search(q){q=q.trim().toLowerCase();let arr=characters.filter(c=>(c.name+" "+c.role+" "+c.ref+" "+c.themes.join(" ")).toLowerCase().includes(q));$("#searchResults").innerHTML=q?(arr.length?arr.map(c=>`<div class="result" data-person="${c.id}"><b>${c.name}</b><span>${c.role} · ${c.ref}</span></div>`).join(""):`<div class="empty">Nenhum resultado encontrado.</div>`):`<div class="empty">Digite um personagem ou palavra para pesquisar.</div>`;$$("#searchResults [data-person]").forEach(x=>x.onclick=()=>openPerson(x.dataset.person))}
$("#mainSearch").addEventListener("input",e=>{if(e.target.value.length){$("#searchInput").value=e.target.value;go("pesquisa");search(e.target.value)}});$("#searchInput").addEventListener("input",e=>search(e.target.value));
function generateOutline(e){e.preventDefault();let topic=$("#outlineTopic").value||"Estudo bíblico",ref=$("#outlineText").value||"Referências selecionadas",goal=$("#outlineGoal").value,time=$("#outlineTime").value,n=+$("#outlinePoints").value[0];let c=characters.find(x=>x.name.toLowerCase()===topic.toLowerCase());let points=c?c.sections.slice(0,n):Array.from({length:n},(_,i)=>[`Ponto ${i+1}`,`Desenvolva este ponto usando ${ref} e destaque a aplicação prática para a igreja.`]);let html=`<div class="outline"><span class="tag">ESBOÇO GERADO · ${goal.toUpperCase()} · ${time}</span><h2>${topic}</h2><p><b>Texto base:</b> ${ref}</p><h3>Introdução</h3><p>Apresente o contexto do tema, leia o texto base e mostre por que essa mensagem é relevante.</p>${points.map((p,i)=>`<div class="section"><h3>${i+1}. ${p[0]}</h3><p>${p[1]}</p><p><b>Aplicação:</b> Como essa verdade pode ser colocada em prática hoje?</p></div>`).join("")}<div class="section"><h3>Conclusão</h3><p>Retome a mensagem principal, destaque a aplicação e conduza a uma reflexão final.</p></div><div class="save-row"><button class="primary" onclick="saveStudy()">⭐ Salvar estudo</button></div></div>`;$("#outlineOutput").innerHTML=html}
$("#outlineForm").addEventListener("submit",generateOutline);
function saveStudy(){let data={topic:$("#outlineTopic").value||"Estudo bíblico",text:$("#outlineText").value||"",date:new Date().toLocaleDateString("pt-BR"),html:$("#outlineOutput").innerHTML};let list=JSON.parse(localStorage.getItem("bibStudies")||"[]");list.unshift(data);localStorage.setItem("bibStudies",JSON.stringify(list));alert("Estudo salvo!");renderSaved()}
function renderSaved(){let list=JSON.parse(localStorage.getItem("bibStudies")||"[]");$("#savedStudies").innerHTML=list.length?list.map((x,i)=>`<div class="saved-item"><b>${x.topic}</b><small>${x.text||"Sem texto base"} · ${x.date}</small><div style="margin-top:10px"><button class="secondary" onclick="viewSaved(${i})">Abrir</button> <button class="secondary" onclick="deleteSaved(${i})">Excluir</button></div></div>`).join(""):`<div class="empty">Você ainda não salvou nenhum estudo.</div>`}
function viewSaved(i){let list=JSON.parse(localStorage.getItem("bibStudies")||"[]");$("#outlineOutput").innerHTML=list[i].html;go("esboco")}
function deleteSaved(i){let list=JSON.parse(localStorage.getItem("bibStudies")||"[]");list.splice(i,1);localStorage.setItem("bibStudies",JSON.stringify(list));renderSaved()}
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("dark",document.body.classList.contains("dark"))};if(localStorage.getItem("dark")==="true")document.body.classList.add("dark");
renderCharacters();renderThemes();search("");
$$("[data-person]").forEach(x=>x.onclick=()=>openPerson(x.dataset.person));
